FeedBack.App/Controllers/Api_Controller/FeedbackApiController.cs
using FeedBack.Entity;
using FeedBack.Manager.FeedBackCollection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace FeedBackCollection.Controllers.Api_Controller
{
    
    public class FeedbackApiController : ApiController
    {

        FeedBackCollectionManager feedBackCollectionManager = new FeedBackCollectionManager();
        // GET: api/FeedbackApi
        public IEnumerable<Post> Get()
        {
            return feedBackCollectionManager.GetPostsWithDetails();
        }

        // GET: api/FeedbackApi/5
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/FeedbackApi
        public void Post([FromBody]string value)
        {
        }

        // PUT: api/FeedbackApi/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/FeedbackApi/5
        public void Delete(int id)
        {
        }
    }
}

FeedBack.App/Controllers/FeedBackCollectionController.cs
using FeedBack.Entity;
using FeedBack.Manager.FeedBackCollection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Net.Http;

namespace FeedBackCollection.Controllers
{
    public class FeedBackCollectionController : Controller
    {
        FeedBackCollectionManager feedBackCollectionManager = new FeedBackCollectionManager();
        public ActionResult FeedBackCollectionDetails(int? page, string Search_Data, string Filter_Value)
        {
            

            IEnumerable<Post> posts = null;

            if (Search_Data != null)
            {
                page = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }

            ViewBag.FilterValue = Search_Data;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44303/api/");
                //HTTP GET
                var responseTask = client.GetAsync("feedbackApi");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Post>>();
                    readTask.Wait();

                    posts = readTask.Result;
                }
                else //web api sent error response 
                {
                    //log response status here..

                    posts = Enumerable.Empty<Post>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }


            if (!String.IsNullOrEmpty(Search_Data))
            {
                posts = posts.Where(s => s.PostMessage.ToUpper().Contains(Search_Data.ToUpper()));
            }
           
            int pageNumber = (page ?? 1);
            int pageSize = 15;

            return View(posts.ToPagedList(pageNumber, pageSize));
        }
    }
}

FeedBack.App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeedBack.App.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FeedBack.App/Views/FeedBackCollection/FeedBackCollectionDetails.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<FeedBack.Entity.Post>

@{
    ViewBag.Title = "FeedBackCollectionDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    FeedBack.Entity.Post post = new FeedBack.Entity.Post();
}
<br />

@using (Html.BeginForm("FeedBackCollectionDetails", "FeedBackCollection", FormMethod.Get))
{
    <div class="row gutters-8">
        <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
            @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @class = "Search form-control", @placeholder = "Search Post" })
        </div>
        <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
            <button style="height:45px !important; padding-top:10px" type="submit" value="Find" id="find" title="Search" class="btn btn-info">Search</button>
        </div>
    </div>
}

<div class="table-responsive" style="overflow-y: hidden;">
    <table class="table display data-table text-nowrap">
        @foreach (var posts in Model.GroupBy(p => p.PostMessage, (key, items) => new
        {
            PostMessage = key,
            CreateTime = items.Select(p => p.CreateDate.ToLocalTime()).FirstOrDefault(),
            User = items.Select(p => p.UserName).FirstOrDefault(),
            CommentCount = items.Sum(p => p.Comments.Count),
            Comments = items.Select(p => p.Comments.ToList())
        }))
        {

            <thead>
                <tr>
                    <th>@posts.PostMessage</th>
                    <th>@posts.User</th>
                    <th>@posts.CreateTime</th>
                    <th>@posts.CommentCount Comments</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var cm in posts.Comments)
                {
                    foreach (var c in cm)
                    {
                        <tr>
                            <td>@c.CommentMsg</td>
                            <td>@c.UserName</td>
                            <td>@c.CreateDate.ToLocalTime()</td>
                            <td><i class="fa fa-arrow-up" style="color:green"></i>@c.YesCount &nbsp; <i class="fa fa-arrow-down" style="color:red"></i>@c.NoCount</td>
                        </tr>
                    }
                }
            </tbody>

        }
    </table>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("FeedBackCollectionDetails", new { page, Filter_Value = ViewBag.FilterValue }), PagedListRenderOptions.ClassicPlusFirstAndLast)
</div>

FeedBack.App/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FeedBack.App/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FeedBack.App/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FeedBack.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    <li>@Html.ActionLink("Post Details", "FeedBackCollectionDetails", "FeedBackCollection")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>